### ISSUE TITLE
服务器无法往qq群发送聊天消息

### ISSUE THREAD

**Issue by Tsurumaki-Kokoro** [DreamVoid/Chat2QQ#34]
<strong>问题描述</strong>

从服务器往qq群发送聊天消息的时候会发生如下报错，且群收不到消息，其他功能都正常

<strong>复现方法</strong>

1. 从服务器往群内发送消息

<strong>版本类型</strong>

* Minecraft 服务端版本：1.18.2
* MiraiMC 插件版本：1.6
* Chat2QQ 插件版本：1.5

<strong>服务器日志</strong>
```
[13:20:52 INFO]: [world] Ayase_Eli_: 1 
[13:20:52 WARN]: [MiraiMC] Plugin Chat2QQ v1.5 generated an exception while executing task 489
java.lang.NullPointerException: Cannot invoke "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.sendGroupMessage(String, long, String)" because "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.INSTANCE" is null
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.lambda$run$0(BukkitPlugin.java:94) ~[Chat2QQ-Bukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.lambda$run$1(BukkitPlugin.java:92) ~[Chat2QQ-Bukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.run(BukkitPlugin.java:92) ~[Chat2QQ-Bukkit.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-260]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-260]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-260]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by DreamVoid** [comment]
miraimc相关，请移步。
