### ISSUE TITLE
BC服，从游戏内向群内发送消息时出现错误

### ISSUE THREAD

**Issue by xiamo070091** [DreamVoid/Chat2QQ#41]
<strong>问题描述</strong>

BC服，从游戏内向群内发送消息时出现错误
从QQ群内发送消息正常

<strong>复现方法</strong>

1. 使用指令/qchat 消息就报错
2. 直接使用Mirai sendgroupmessage发送没问题

<strong>版本类型</strong>
1. 使用的JDK为zulujdk最新版，系统centos
2. 使用的BC服务端核心为[HexaCord](https://github.com/HexagonMC/BungeeCord)
* Minecraft 服务端版本：HexaCord-280
* MiraiMC 插件版本：1.6
* Chat2QQ 插件版本：1.5

<strong>服务器日志</strong>

```
16:19:24 [INFO] 已发送QQ群聊天消息！
16:19:24 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@1187c9e8, id=39, owner=me.dreamvoid.chat2qq.bungee.BungeePlugin@4d41ba0f, task=me.dreamvoid.chat2qq.bungee.commands.qchat$$Lambda$858/1475982439@3078cac, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at me.dreamvoid.chat2qq.bungee.commands.qchat.lambda$execute$0(qchat.java:60)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at me.dreamvoid.chat2qq.bungee.commands.qchat.lambda$execute$1(qchat.java:58)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at me.dreamvoid.chat2qq.bungee.commands.qchat.lambda$execute$2(qchat.java:58)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)

```

**Comment by DreamVoid** [comment]
完整日志
