### ISSUE TITLE
qq群发消息 在后台会报错  我没有开#才转发  玩家进服也会  开久就报错 然后崩服

### ISSUE THREAD

**Issue by seyink** [DreamVoid/Chat2QQ#42]
<strong>问题描述</strong>

qq群发消息 在后台会报错  我没有开#才转发  玩家进服也会  开久就报错 然后崩服

<strong>复现方法</strong>

1. qq群发消息
2. 进入服务器

<strong>版本类型</strong>

* Minecraft 服务端版本：Paper-1.18.1  216
* MiraiMC 插件版本：Bukkit最新版
* Chat2QQ 插件版本：1.5

<strong>服务器日志</strong>

```
### 玩家进入服务器
[16:25:15] [Craft Scheduler Thread - 13 - Chat2QQ/WARN]: [MiraiMC] Plugin Chat2QQ v1.5 generated an exception while executing task 724
java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.contact.Group.sendMessage(net.mamoe.mirai.message.data.Message)" because "this.group" is null
	at me.dreamvoid.miraimc.api.bot.MiraiGroup.sendMessageMirai(MiraiGroup.java:48) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.chat2qq.bukkit.listener.onPlayerJoin$1.lambda$run$0(onPlayerJoin.java:30) ~[Chat2QQ-Bukkit.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at me.dreamvoid.chat2qq.bukkit.listener.onPlayerJoin$1.lambda$run$1(onPlayerJoin.java:28) ~[Chat2QQ-Bukkit.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at me.dreamvoid.chat2qq.bukkit.listener.onPlayerJoin$1.run(onPlayerJoin.java:28) ~[Chat2QQ-Bukkit.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-216]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-216]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
### qq群发消息
[16:47:07] [DefaultDispatcher-worker-3/FATAL]: Thread DefaultDispatcher-worker-3 failed main thread check: ChunkHolder update
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:314) ~[?:?]
	at net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:278) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1130) ~[?:?]
	at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1547) ~[?:?]
	at net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45) ~[?:?]
	at net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:253) ~[adventure-api-4.9.3.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:227) ~[adventure-api-4.9.3.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1767) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1739) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcastMessage(CraftServer.java:644) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:58) ~[Chat2QQ-Bukkit.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-216]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:97) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[MiraiMC-Bukkit.jar:?]
[16:47:07] [DefaultDispatcher-worker-3/ERROR]: Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.5
java.lang.IllegalStateException: Asynchronous ChunkHolder update!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:314) ~[?:?]
	at net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:278) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1130) ~[?:?]
	at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1547) ~[?:?]
	at net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45) ~[?:?]
	at net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:253) ~[adventure-api-4.9.3.jar:?]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:227) ~[adventure-api-4.9.3.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1767) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1739) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcastMessage(CraftServer.java:644) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:58) ~[Chat2QQ-Bukkit.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-216]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:97) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[MiraiMC-Bukkit.jar:?]
```

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/Chat2QQ/issues/29
