### ISSUE TITLE
通过 Geyser 连接的玩家看不到消息, 报错, 刷屏 java.lang.NullPointerException

### ISSUE THREAD

**Issue by From-pErfo** [DreamVoid/Chat2QQ#44]
### 问题描述

基岩版玩家看不到QQ群转发的消息, Java版没有问题
有时候每发送一条消息就会报错, 或者大量刷屏 `java.lang.NullPointerException`
[刷屏导致日志文件超过12MB]

以下的日志来自本地测试, 基岩版能收到消息, 但插件还在报错

### 复现方法

1. 加载插件 `floodgate-spigot, Geyser-Spigot, ProtocolLib, Chat2QQ-Bukkit, MiraiMC-Bukkit, ViaBackwards`
2. 运行服务端, 加入基岩版玩家
3. 在QQ群里发送消息
4. 控制台出现错误

### 服务端类型

Bukkit

### 服务端版本

git-Mirai-7838cca (MC: 1.18.2)

### MiraiMC 插件版本

1.6

### Chat2QQ 插件版本

1.5

### 服务端日志

```text
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12-LTS) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[11:10:29 INFO]: [Hydrogen] Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/D:/Desktop/Mirai/versions/1.18.2/mirai-1.18.2.jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[11:10:29 INFO]: [Hydrogen] Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/D:/Desktop/Mirai/versions/1.18.2/mirai-1.18.2.jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[11:10:29 INFO]: [Hydrogen] Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/D:/Desktop/Mirai/versions/1.18.2/mirai-1.18.2.jar!/com/google/common/collect/HydrogenEntrySet.class)
[11:10:29 INFO]: [Hydrogen] Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/D:/Desktop/Mirai/versions/1.18.2/mirai-1.18.2.jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[11:10:34 INFO]: [STDOUT]: No global eula file found at C:\Users\Nm70727\eula.txt
[11:10:34 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:10:36 INFO]: Loaded 7 recipes
[11:10:39 INFO]: Starting minecraft server version 1.18.2
[11:10:39 INFO]: Loading properties
[11:10:39 INFO]: This server is running Mirai version git-Mirai-7838cca (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 7838cca on purpur/1.18.2)
[11:10:39 INFO]: Server Ping Player Sample Count: 0
[11:10:39 INFO]: Using 8 threads for Netty based IO
[11:10:39 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[11:10:39 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[11:10:39 INFO]: Default game type: SURVIVAL
[11:10:39 INFO]: Generating keypair
[11:10:40 INFO]: Starting Minecraft server on *:25565
[11:10:40 INFO]: Using default channel type
[11:10:40 INFO]: Paper: Using Java 11 compression from Velocity.
[11:10:40 INFO]: Paper: Using Java cipher from Velocity.
[11:10:41 INFO]: [MiraiMC] Loading MiraiMC v1.6
[11:10:42 INFO]: [MiraiMC] Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[11:10:42 INFO]: [MiraiMC] Verifying mirai-core-all-2.11.0-M2.2.jar
[11:10:43 INFO]: [MiraiMC] Loading library mirai-core-all-2.11.0-M2.2.jar
[11:10:43 INFO]: [ViaVersion] Loading ViaVersion v4.2.1
[11:10:43 INFO]: [ViaVersion] ViaVersion 4.2.1 is now loaded, injecting!
[11:10:43 INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[11:10:43 INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[11:10:43 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[11:10:43 INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[11:10:43 INFO]: [ViaVersion] Loading block connection mappings ...
[11:10:43 INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[11:10:43 INFO]: [floodgate] Loading floodgate v2.1.0-SNAPSHOT
[11:10:44 INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[11:10:44 INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[11:10:44 INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[11:10:45 INFO]: [floodgate] 启动 Floodgate，耗时1,393ms
[11:10:45 INFO]: [ViaBackwards] Loading ViaBackwards v4.2.1
[11:10:45 INFO]: [ViaBackwards] Loading translations...
[11:10:45 INFO]: [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.11 -> 1.10 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.12 -> 1.11 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.13 -> 1.12 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.13.2 -> 1.13 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.14 -> 1.13.2 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.15 -> 1.14 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.16 -> 1.15 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.16.2 -> 1.16 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.17 -> 1.16.2 mappings...
[11:10:45 INFO]: [ViaBackwards] Loading 1.18 -> 1.17 mappings...
[11:10:45 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[11:10:47 INFO]: [MiraiMC] Loading Chat2QQ v1.5
[11:10:47 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.0.2-SNAPSHOT
[11:10:47 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[11:10:47 INFO]: [ProtocolLib] Started structure compiler thread.
[11:10:47 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[11:10:47 WARN]: The server will make no attempt to authenticate usernames. Beware.
[11:10:47 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[11:10:47 WARN]: You will not be offered any support as long as the server allows offline-mode players to join.
[11:10:47 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[11:10:47 INFO]: Preparing level "world"
[11:10:49 INFO]: [MiraiMC] Enabling MiraiMC v1.6
[11:10:49 INFO]: [MiraiMC] Mirai working dir: default
[11:10:49 INFO]: [MiraiMC] Starting Mirai-Events listener.
[11:10:50 INFO]: [MiraiMC] Loading auto-login file.
[11:10:50 INFO]: [MiraiMC] Registering commands.
[11:10:50 INFO]: [MiraiMC] Initializing SQLite database.
[11:10:50 INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[11:10:50 INFO]: [ViaVersion] Enabling ViaVersion v4.2.1
[11:10:50 INFO]: [floodgate] Enabling floodgate v2.1.0-SNAPSHOT
[11:10:50 INFO]: [ViaBackwards] Enabling ViaBackwards v4.2.1
[11:10:50 INFO]: [MiraiMC] Enabling Chat2QQ v1.5
[11:10:50 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.0.2-SNAPSHOT
[11:10:51 INFO]: [Geyser-Spigot] 成功自动加载Floodgate密钥
[11:10:51 INFO]: [Geyser-Spigot] ******************************************
[11:10:51 INFO]: [Geyser-Spigot]
[11:10:51 INFO]: [Geyser-Spigot] 加载 Geyser 中, 版本 2.0.2-SNAPSHOT (git-master-877301a)
[11:10:51 INFO]: [Geyser-Spigot]
[11:10:51 INFO]: [Geyser-Spigot] ******************************************
[11:10:56 INFO]: [Geyser-Spigot] 成功加载Floodgate密钥!
[11:10:56 INFO]: [Geyser-Spigot] Geyser正在启动 0.0.0.0:19132
[11:10:56 INFO]: [Geyser-Spigot] 完成 (5.15s)! 执行/geyser help 来获取帮助信息!
[11:10:56 INFO]: Running delayed init tasks
[11:10:56 INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[11:10:56 INFO]: [MiraiMC] [AutoLogin] Auto login bot account: 2469678133 Protocol: ANDROID_PHONE
[11:10:56 INFO]: [ViaVersion] ViaVersion detected server version: 1.18.2 (758)
[11:10:56 INFO]: [MiraiMC] 登录新的机器人账号: 2469678133, 协议: ANDROID_PHONE
[11:10:56 ERROR]: [ViaVersion] ************************************************
[11:10:56 ERROR]: [ViaVersion] You are using unsupported software and may encounter unforeseeable issues.
[11:10:56 ERROR]: [ViaVersion]
[11:10:56 ERROR]: [ViaVersion] We strongly advise against using Yatopia:
[11:10:56 ERROR]: [ViaVersion] You are using server software that - outside of possibly breaking ViaVersion - can also cause severe damage to your server's integrity as a whole.
[11:10:56 ERROR]: [ViaVersion]
[11:10:56 ERROR]: [ViaVersion] We will not provide support in case you encounter issues possibly related to this software.
[11:10:56 ERROR]: [ViaVersion] ************************************************
[11:10:57 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[11:10:57 INFO]: Done (17.848s)! For help, type "help"
[11:10:57 INFO]: Timings Reset
[11:11:00 INFO]: [MiraiMC] CiAt(2469678133) 登录成功
[11:11:09 INFO]: [Geyser-Spigot] /192.168.100.248:60003 尝试连接!
[11:11:10 INFO]: [Geyser-Spigot] 玩家以 NM70727 的用户名建立了连接
[11:11:10 INFO]: [Geyser-Spigot] NM70727 (登录为: NM70727) 已连接到 Java 服务器
[11:11:10 INFO]: UUID of player .NM70727 is 00000000-0000-0000-0009-01fc4c122978
[11:11:10 INFO]: [floodgate] Floodgate 玩家 .NM70727 加入了 (UUID: 00000000-0000-0000-0009-01fc4c122978)
[11:11:11 INFO]: .NM70727 joined the game
[11:11:11 INFO]: .NM70727[/192.168.100.248:0] logged in with entity id 1 at ([world]194.44398, 65.47647, 81.45017)
[11:11:18 INFO]: [ProtocolLib] The updater found an update, and has readied it to be loaded the next time the server restarts/reloads.
[11:11:28 ERROR]: Thread DefaultDispatcher-worker-4 failed main thread check: ChunkHolder update
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:329) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:289) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1156) ~[?:?]
        at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1658) ~[?:?]
        at net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45) ~[?:?]
        at net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254) ~[adventure-api-4.10.1.jar:?]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228) ~[adventure-api-4.10.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1782) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1754) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcastMessage(CraftServer.java:641) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:58) ~[QQ_Chat2QQ-Bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor6.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:git-Mirai-7838cca]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:642) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:97) ~[QQ_MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[QQ_MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[QQ_MiraiMC-Bukkit.jar:?]
[11:11:28 ERROR]: Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.5
java.lang.IllegalStateException: Asynchronous ChunkHolder update!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:329) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:289) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1156) ~[?:?]
        at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1658) ~[?:?]
        at net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45) ~[?:?]
        at net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254) ~[adventure-api-4.10.1.jar:?]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228) ~[adventure-api-4.10.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1782) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1754) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcastMessage(CraftServer.java:641) ~[mirai-1.18.2.jar:git-Mirai-7838cca]
        at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:58) ~[QQ_Chat2QQ-Bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor6.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:git-Mirai-7838cca]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:642) ~[mirai-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:97) ~[QQ_MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[QQ_MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[QQ_MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[QQ_MiraiMC-Bukkit.jar:?]
```

### 额外说明

这个问题在 purpur 核心上也出现过, 我没有测试 paper

这是刷 `java.lang.NullPointerException` 的服务器控制台
![image](https://user-images.githubusercontent.com/59365724/162554621-81bf6ce5-2ce1-4044-b3ea-d68c165b05aa.png)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/Chat2QQ/issues/29
NPE问题不认为是Chat2QQ，如有日志提供请新开issue
