### ISSUE TITLE
指令用不了

### ISSUE THREAD

**Issue by loolksama** [DreamVoid/Chat2QQ#48]
### 问题描述

使用/qchat报错
MiraiHttpAPI.INSTANCE is null

### 复现方法

1. /qchat
2. 报错

### 服务端类型

BungeeCord

### 服务端版本

Bc最新构建

### MiraiMC 插件版本

1.6.1

### Chat2QQ 插件版本

1.5

### 服务端日志

```text
>qchat 1
15:35:04 [信息] 已发送QQ群聊天消息！
15:35:04 [严重] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@13e547a9, id=152, owner=me.dreamvoid.chat2qq.bungee.BungeePlugin@3e755d5f, task=me.dreamvoid.chat2qq.bungee.commands.qchat$$Lambda$1181/0x0000000801285998@7bdf8c92, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: Cannot invoke "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.sendGroupMessage(String, long, String)" because "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.INSTANCE" is null
    at me.dreamvoid.chat2qq.bungee.commands.qchat.lambda$execute$0(qchat.java:60)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at me.dreamvoid.chat2qq.bungee.commands.qchat.lambda$execute$1(qchat.java:58)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at me.dreamvoid.chat2qq.bungee.commands.qchat.lambda$execute$2(qchat.java:58)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

### 额外说明

Java17
重启无效

### 协议

- [x] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by loolksama** [comment]
开了还是没得用 尬住了

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/Chat2QQ/issues/43
