### ISSUE TITLE
1.6版本报错 回退1.5恢复

### ISSUE THREAD

**Issue by suxingye** [DreamVoid/Chat2QQ#57]
### 问题描述

升级1.6后粘贴新的配置文件 热加载插件报错

### 复现方法

1. 使用purpur1.19服务端加载插件

### 服务端类型

Bukkit

### 服务端版本

purpur1.19

### MiraiMC 插件版本

1.6.1

### Chat2QQ 插件版本

1.6

### 服务端日志

```text
[09:55:42 ERROR]: Could not pass event PlayerJoinEvent to Chat2QQ v1.6
java.lang.NoClassDefFoundError: me/dreamvoid/miraimc/httpapi/exception/AbnormalStatusException
	at me.dreamvoid.chat2qq.bukkit.listener.onPlayerJoin.onPlayerJoinEvent(onPlayerJoin.java:27) ~[Chat2QQ-Bukkit (1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor250.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1684]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:365) ~[purpur-1.19.jar:git-Purpur-1684]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:307) ~[purpur-1.19.jar:git-Purpur-1684]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:341) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:577) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1609) ~[purpur-1.19.jar:git-Purpur-1684]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1684]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1684]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1684]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1684]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.dreamvoid.miraimc.httpapi.exception.AbnormalStatusException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 17 more
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
miraimc更新到1.7
