### ISSUE TITLE
[已解决]服务器中发送消息时无法发送到qq群

### ISSUE THREAD

**Issue by Zhou-Shilin** [DreamVoid/Chat2QQ#62]
### 问题描述

打完 /qchat test 后报错：
`[13:17:09 INFO]: 已发送QQ群聊天消息！
[13:17:09 WARN]: [MiraiMC] Plugin Chat2QQ v1.6 generated an exception while executing task 126603
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:191) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.contact.SendMessageHandler$sendMessagePacket$1.invokeSuspend(SendMessageHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1412) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:79) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:193) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### 复现方法

1. 使用1.19paper端安装miraimc和本插件
2. 配置完并让机器人加群
3. 输入 /qchat test 然后会报错
4. 注意，其实我是用了一段时间（没问题）后突然发现的

### 服务端类型

Bukkit

### 服务端版本

Paper-1.19

### MiraiMC 插件版本

1.7

### Chat2QQ 插件版本

1.6

### 服务端日志

```text
[13:17:09 INFO]: 已发送QQ群聊天消息！
[13:17:09 WARN]: [MiraiMC] Plugin Chat2QQ v1.6 generated an exception while executing task 126603
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:191) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.contact.SendMessageHandler$sendMessagePacket$1.invokeSuspend(SendMessageHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1412) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:79) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:193) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by TT092** [comment]
xd我也一样的bug欸

**Comment by TT092** [comment]
并且向服务器发消息没问题，但是向qq群一样的报错

**Comment by Zhou-Shilin** [comment]
> 并且向服务器发消息没问题，但是向qq群一样的报错

我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa

**Comment by TT092** [comment]
> > 并且向服务器发消息没问题，但是向qq群一样的报错
> 
> 我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa

厉害厉害

**Comment by TT092** [comment]
> > 并且向服务器发消息没问题，但是向qq群一样的报错
> 
> 我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa

重新过人机验证是吗

**Comment by Zhou-Shilin** [comment]
> > > 并且向服务器发消息没问题，但是向qq群一样的报错
> > 
> > 
> > 我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa
> 
> 重新过人机验证是吗

对的，这样就会被解封

**Comment by DreamVoid** [comment]
已解决就自己把问题关掉

**Comment by TT092** [comment]
> > > > 并且向服务器发消息没问题，但是向qq群一样的报错
> > > 
> > > 
> > > 我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa
> > 
> > 
> > 重新过人机验证是吗
> 
> 对的，这样就会被解封

xd,我这边点红点没人机验证，只有重新发送

**Comment by 848244210** [comment]
> > > > > 并且向服务器发消息没问题，但是向qq群一样的报错
> > > > 
> > > > 
> > > > 我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa
> > > 
> > > 
> > > 重新过人机验证是吗
> > 
> > 
> > 对的，这样就会被解封
> 
> xd,我这边点红点没人机验证，只有重新发送
最新qq 下面可以看到违规申诉

**Comment by Zhou-Shilin** [comment]
> > > > > 并且向服务器发消息没问题，但是向qq群一样的报错
> > > > 
> > > > 
> > > > 我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa
> > > 
> > > 
> > > 重新过人机验证是吗
> > 
> > 
> > 对的，这样就会被解封
> 
> xd,我这边点红点没人机验证，只有重新发送

先重新发送，然后会有提示的～

**Comment by TT092** [comment]
> > > > > > 并且向服务器发消息没问题，但是向qq群一样的报错
> > > > > 
> > > > > 
> > > > > 我找到解决办法了，手机登录机器人账号，然后发条消息，点红点，通过人机验证即可awa
> > > > 
> > > > 
> > > > 重新过人机验证是吗
> > > 
> > > 
> > > 对的，这样就会被解封
> > 
> > 
> > xd,我这边点红点没人机验证，只有重新发送
> 
> 先重新发送，然后会有提示的～

谢谢你xd
