### ISSUE TITLE
BC端当玩家在聊天框里输入指令控制台会报错，但能正确发送消息

### ISSUE THREAD

**Issue by g2213swo** [DreamVoid/Chat2QQ#65]
### 问题描述

当玩家正常使用/qchat的时候，控制台将会输出报错，报错内容可能是未和1.19的聊天验证做兼容。MiraiMC使用的是默认配置，插件启动时无任何报错。

### 复现方法

1. 正常使用/qchat

### 服务端类型

BungeeCord

### 服务端版本

git-Purpur-1835 (MC: 1.19.2)* || git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT

### MiraiMC 插件版本

This server is running MiraiMC version 1.7 by DreamVoid

### Chat2QQ 插件版本

This server is running Chat2QQ version 1.6 by DreamVoid (MiraiMC version 1.7)

### 服务端日志

```text
[20:55:28] [Netty Worker IO Thread #26/WARN]: Error in dispatching command
java.lang.UnsupportedOperationException: Cannot spoof chat on this client version!
	at net.md_5.bungee.UserConnection.chat(UserConnection.java:449) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at me.dreamvoid.chat2qq.bungee.commands.qchat.execute(qchat.java:90) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:194) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:171) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at net.md_5.bungee.protocol.packet.ClientCommand.handle(ClientCommand.java:77) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-506.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### 额外说明

此问题似乎在https://github.com/SpigotMC/BungeeCord/issues/3327有说明，需要插件作者兼容。

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by g2213swo** [comment]
这个选项在哪里开关呢？我仔细寻找后并没有找到。
