### ISSUE TITLE
服务器消息无法转发到q群。Q群消息,刚开始能转发到服务器，后面就无法转发

### ISSUE THREAD

**Issue by shulng** [DreamVoid/Chat2QQ#78]
### 问题描述

[21:57:25 ERROR]: Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.6
java.lang.RuntimeException: 处理数据时出现异常，请检查MiraiMC数据库配置是否正确
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:132) ~[MiraiMC-Bukkit.jar:?]
        at Chat2QQ-Bukkit.jar/me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:116) ~[Chat2QQ-Bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:55) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:124) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
Caused by: java.sql.SQLTransientConnectionException: MiraiMC-SQLite - Connection is not available, request timed out after 30000ms (total=15, active=15, idle=0, waiting=1)
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99) ~[HikariCP-5.1.0.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.SQLite.getConnection(SQLite.java:72) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.DatabaseHandler.executeQuery(DatabaseHandler.java:32) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:129) ~[MiraiMC-Bukkit.jar:?]
        ... 21 more
[21:57:44 ERROR]: Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.6
java.lang.RuntimeException: 处理数据时出现异常，请检查MiraiMC数据库配置是否正确
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:132) ~[MiraiMC-Bukkit.jar:?]
        at Chat2QQ-Bukkit.jar/me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:116) ~[Chat2QQ-Bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:55) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:124) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
Caused by: java.sql.SQLTransientConnectionException: MiraiMC-SQLite - Connection is not available, request timed out after 30000ms (total=15, active=15, idle=0, waiting=0)
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99) ~[HikariCP-5.1.0.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.SQLite.getConnection(SQLite.java:72) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.DatabaseHandler.executeQuery(DatabaseHandler.java:32) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:129) ~[MiraiMC-Bukkit.jar:?]
        ... 21 more

### 复现方法

1. q 群发消息

### 服务端类型

Bukkit

### 服务端版本

Lumina-1.20.6

### MiraiMC 插件版本

最新CI

### Chat2QQ 插件版本

最新CI

### 服务端日志

```text
[21:57:25 ERROR]: Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.6
java.lang.RuntimeException: 处理数据时出现异常，请检查MiraiMC数据库配置是否正确
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:132) ~[MiraiMC-Bukkit.jar:?]
        at Chat2QQ-Bukkit.jar/me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:116) ~[Chat2QQ-Bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:55) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:124) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
Caused by: java.sql.SQLTransientConnectionException: MiraiMC-SQLite - Connection is not available, request timed out after 30000ms (total=15, active=15, idle=0, waiting=1)
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99) ~[HikariCP-5.1.0.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.SQLite.getConnection(SQLite.java:72) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.DatabaseHandler.executeQuery(DatabaseHandler.java:32) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:129) ~[MiraiMC-Bukkit.jar:?]
        ... 21 more
[21:57:44 ERROR]: Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.6
java.lang.RuntimeException: 处理数据时出现异常，请检查MiraiMC数据库配置是否正确
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:132) ~[MiraiMC-Bukkit.jar:?]
        at Chat2QQ-Bukkit.jar/me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:116) ~[Chat2QQ-Bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:55) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:124) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[mirai-core-all-2.16.0-all.jar:2.16.0]
Caused by: java.sql.SQLTransientConnectionException: MiraiMC-SQLite - Connection is not available, request timed out after 30000ms (total=15, active=15, idle=0, waiting=0)
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-5.1.0.jar:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99) ~[HikariCP-5.1.0.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.SQLite.getConnection(SQLite.java:72) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.database.DatabaseHandler.executeQuery(DatabaseHandler.java:32) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.api.MiraiMC$Bind.getBind(MiraiMC.java:129) ~[MiraiMC-Bukkit.jar:?]
        ... 21 more
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by shulng** [comment]
附加报错信息
[01:02:07] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Chat2QQ v1.6
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:532) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:258) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:245) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:190) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:159) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at org.bukkit.scheduler.BukkitRunnable.runTaskAsynchronously(BukkitRunnable.java:63) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at Chat2QQ-Bukkit.jar/me.dreamvoid.chat2qq.bukkit.listener.onPlayerMessage.onPlayerChat(onPlayerMessage.java:66) ~[Chat2QQ-Bukkit.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:55) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[lumina-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2459) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2576) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$12(ServerGamePacketListenerImpl.java:2231) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[lumina-1.20.6.jar:1.20.6-DEV-335a655]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
